import "@hotwired/turbo-rails";
import { Application } from "@hotwired/stimulus";
import AgentFormController from "./controllers/agent_form_controller";
import AttachmentPreviewController from "./controllers/attachment_preview_controller";
import AttachmentUploadController from "./controllers/attachment_upload_controller";
import AssociationPickerController from "./controllers/association_picker_controller";
import AssociationCreatedController from "./controllers/association_created_controller";
import CategoryMultiselectController from "./controllers/category_multiselect_controller";
import CategorySelectorController from "./controllers/category_selector_controller";
import ClipboardController from "./controllers/clipboard_controller";
import ConditionalFieldController from "./controllers/conditional_field_controller";
import DatePickerController from "./controllers/date_picker_controller";
import DiagnosisEventPopoverController from "./controllers/diagnosis_event_popover_controller";
import EmailInputController from "./controllers/email_input_controller";
import EchartsController from "./controllers/echarts_controller";
import FeedbackController from "./controllers/feedback_controller";
import GbrainPageEditorController from "./controllers/gbrain_page_editor_controller";
import HistoryNavigationController from "./controllers/history_navigation_controller";
import HierarchyTableController from "./controllers/hierarchy_table_controller";
import InlineCellController from "./controllers/inline_cell_controller";
import LongTextController from "./controllers/long_text_controller";
import MarkdownController from "./controllers/markdown_controller";
import ModalController from "./controllers/modal_controller";
import OperatorDialogController from "./controllers/operator_dialog_controller";
import OzonChatInboxController from "./controllers/ozon_chat_inbox_controller";
import PageTranslationController from "./controllers/page_translation_controller";
import PopoverMultiselectFilterController from "./controllers/popover_multiselect_filter_controller";
import ProfitTrendToggleController from "./controllers/profit_trend_toggle_controller";
import ProfitPeriodFilterController from "./controllers/profit_period_filter_controller";
import ProfitStoreTrendSelectorController from "./controllers/profit_store_trend_selector_controller";
import ProductTreeController from "./controllers/product_tree_controller";
import ResponsibleUserFilterController from "./controllers/responsible_user_filter_controller";
import ShellController from "./controllers/shell_controller";
import SkuBatchFormController from "./controllers/sku_batch_form_controller";
import SkuDetailTabsController from "./controllers/sku_detail_tabs_controller";
import SkuLifecycleTimelineController from "./controllers/sku_lifecycle_timeline_controller";
import SpuSkuFilterController from "./controllers/spu_sku_filter_controller";
import TimeRangeSelectorController from "./controllers/time_range_selector_controller";
import TableRowExpanderController from "./controllers/table_row_expander_controller";
import ToastController from "./controllers/toast_controller";
import WeeklyProfitFilterController from "./controllers/weekly_profit_filter_controller";
import YclawDownloadController from "./controllers/yclaw_download_controller";

window.Stimulus = Application.start();
Stimulus.register("agent-form", AgentFormController);
Stimulus.register("attachment-preview", AttachmentPreviewController);
Stimulus.register("attachment-upload", AttachmentUploadController);
Stimulus.register("association-picker", AssociationPickerController);
Stimulus.register("association-created", AssociationCreatedController);
Stimulus.register("category-multiselect", CategoryMultiselectController);
Stimulus.register("category-selector", CategorySelectorController);
Stimulus.register("clipboard", ClipboardController);
Stimulus.register("conditional-field", ConditionalFieldController);
Stimulus.register("date-picker", DatePickerController);
Stimulus.register("diagnosis-event-popover", DiagnosisEventPopoverController);
Stimulus.register("email-input", EmailInputController);
Stimulus.register("echarts", EchartsController);
Stimulus.register("feedback", FeedbackController);
Stimulus.register("gbrain-page-editor", GbrainPageEditorController);
Stimulus.register("history-navigation", HistoryNavigationController);
Stimulus.register("hierarchy-table", HierarchyTableController);
Stimulus.register("inline-cell", InlineCellController);
Stimulus.register("long-text", LongTextController);
Stimulus.register("markdown", MarkdownController);
Stimulus.register("modal", ModalController);
Stimulus.register("operator-dialog", OperatorDialogController);
Stimulus.register("ozon-chat-inbox", OzonChatInboxController);
Stimulus.register("page-translation", PageTranslationController);
Stimulus.register("popover-multiselect-filter", PopoverMultiselectFilterController);
Stimulus.register("profit-trend-toggle", ProfitTrendToggleController);
Stimulus.register("profit-period-filter", ProfitPeriodFilterController);
Stimulus.register("profit-store-trend-selector", ProfitStoreTrendSelectorController);
Stimulus.register("product-tree", ProductTreeController);
Stimulus.register("responsible-user-filter", ResponsibleUserFilterController);
Stimulus.register("shell", ShellController);
Stimulus.register("sku-batch-form", SkuBatchFormController);
Stimulus.register("sku-detail-tabs", SkuDetailTabsController);
Stimulus.register("sku-lifecycle-timeline", SkuLifecycleTimelineController);
Stimulus.register("spu-sku-filter", SpuSkuFilterController);
Stimulus.register("time-range-selector", TimeRangeSelectorController);
Stimulus.register("table-row-expander", TableRowExpanderController);
Stimulus.register("toast", ToastController);
Stimulus.register("weekly-profit-filter", WeeklyProfitFilterController);
Stimulus.register("yclaw-download", YclawDownloadController);
