import "@hotwired/turbo-rails";
import { Application } from "@hotwired/stimulus";
import ClipboardController from "./controllers/clipboard_controller";
import DatePickerController from "./controllers/date_picker_controller";
import FeedbackController from "./controllers/feedback_controller";
import InlineCellController from "./controllers/inline_cell_controller";
import LongTextController from "./controllers/long_text_controller";
import ModalController from "./controllers/modal_controller";
import OperatorDialogController from "./controllers/operator_dialog_controller";
import PageTranslationController from "./controllers/page_translation_controller";
import ProductTreeController from "./controllers/product_tree_controller";
import ShellController from "./controllers/shell_controller";
import TimeRangeSelectorController from "./controllers/time_range_selector_controller";
import ToastController from "./controllers/toast_controller";

window.Stimulus = Application.start();
Stimulus.register("clipboard", ClipboardController);
Stimulus.register("date-picker", DatePickerController);
Stimulus.register("feedback", FeedbackController);
Stimulus.register("inline-cell", InlineCellController);
Stimulus.register("long-text", LongTextController);
Stimulus.register("modal", ModalController);
Stimulus.register("operator-dialog", OperatorDialogController);
Stimulus.register("page-translation", PageTranslationController);
Stimulus.register("product-tree", ProductTreeController);
Stimulus.register("shell", ShellController);
Stimulus.register("time-range-selector", TimeRangeSelectorController);
Stimulus.register("toast", ToastController);
